name: Terraform Plan

on:
  pull_request:
    branches: [ main ]

jobs:
  plan:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2

      - run: terraform init
      - run: terraform validate
    #   - run: terraform plan